### ISSUE TITLE
雇佣小鸡存在逻辑判断bug

### ISSUE THREAD

**Issue by Neo9393** [TKaxv-7S/Sesame-TK#133]
### 程序版本 / 框架版本 / 模块版本

1.2.6

### 系统版本 / Android版本

colorOS android14

### 详细描述问题发生的具体原因

雇佣好友小鸡时，应该是按照选中的雇佣列表进行遍历雇佣的，但少个判断，若选中雇佣的好友小鸡不在家，则不会遍历雇佣下个在家的好友小鸡。表述有点乱，不知道大神能否理解。
![Screenshot_2024-07-03-09-31-58-92_a66f4987811f41f132433609e46be64d](https://github.com/TKaxv-7S/Sesame-TK/assets/174220847/698b6ad8-bccc-4071-b072-7bd829de1946)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

07:05:41.337 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at tkaxv7s.xposed.sesame.ui.MainActivity$2.run(MainActivity.java:125)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:07:52.421 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
	at android.app.Activity.performResume(Activity.java:8916)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5277)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5338)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:08:10.357 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at tkaxv7s.xposed.sesame.ui.MainActivity$2.run(MainActivity.java:125)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:08:46.876 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
	at android.app.Activity.performResume(Activity.java:8916)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5277)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5338)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:09:48.687 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
	at android.app.Activity.performResume(Activity.java:8916)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5277)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5338)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:10:40.638 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
	at android.app.Activity.performResume(Activity.java:8916)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5277)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5338)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:11:21.027 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
	at android.app.Activity.performResume(Activity.java:8916)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5277)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5338)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:13:06.683 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
	at android.app.Activity.performResume(Activity.java:8916)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5277)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5338)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:13:19.074 ERROR: Statistics, java.lang.RuntimeException: 用户为空，状态保存失败
	at tkaxv7s.xposed.sesame.util.Status.save(Status.java:716)
	at tkaxv7s.xposed.sesame.util.Status.dayClear(Status.java:662)
	at tkaxv7s.xposed.sesame.util.Statistics.resetByCalendar(Statistics.java:110)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:120)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:179)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
	at android.app.Activity.performResume(Activity.java:8916)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5277)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5338)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:64)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:30:16.634 ERROR: AntSports, org.json.JSONException: No value for resultCode
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antSports.AntSports.queryMyHomePage(AntSports.java:181)
	at tkaxv7s.xposed.sesame.model.task.antSports.AntSports.run(AntSports.java:105)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

07:30:16.641 ERROR: AntOcean, org.json.JSONException: No value for resultCode
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antOcean.AntOcean.queryHomePage(AntOcean.java:78)
	at tkaxv7s.xposed.sesame.model.task.antOcean.AntOcean.run(AntOcean.java:58)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

07:30:16.642 ERROR: AntMember, org.json.JSONException: No value for resultCode
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antMember.AntMember.memberSign(AntMember.java:109)
	at tkaxv7s.xposed.sesame.model.task.antMember.AntMember.run(AntMember.java:61)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

08:25:17.534 ERROR: AntFarm, org.json.JSONException: No value for memo
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.hireAnimalAction(AntFarm.java:1771)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.hireAnimal(AntFarm.java:1755)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.run(AntFarm.java:330)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:13:45.965 ERROR: AntForestV2, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String tkaxv7s.xposed.sesame.rpc.RpcBridge.requestString(java.lang.String, java.lang.String)' on a null object reference
	at tkaxv7s.xposed.sesame.hook.ApplicationHook.requestString(ApplicationHook.java:655)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestRpcCall.antdodoPropList(AntForestRpcCall.java:245)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.antdodoPropList(AntForestV2.java:2119)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.run(AntForestV2.java:279)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:13:45.965 ERROR: AntForestV2, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String tkaxv7s.xposed.sesame.rpc.RpcBridge.requestString(java.lang.String, java.lang.String)' on a null object reference
	at tkaxv7s.xposed.sesame.hook.ApplicationHook.requestString(ApplicationHook.java:655)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestRpcCall.queryAnimalStatus(AntForestRpcCall.java:205)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.antdodoCollect(AntForestV2.java:1980)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.run(AntForestV2.java:280)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:13:45.966 ERROR: AntForestV2, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String tkaxv7s.xposed.sesame.rpc.RpcBridge.requestString(java.lang.String, java.lang.String)' on a null object reference
	at tkaxv7s.xposed.sesame.hook.ApplicationHook.requestString(ApplicationHook.java:655)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestRpcCall.consultForSendEnergyByAction(AntForestRpcCall.java:373)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.sendEnergyByAction(AntForestV2.java:1224)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.run(AntForestV2.java:301)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:13:45.966 ERROR: AntForestV2, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String tkaxv7s.xposed.sesame.rpc.RpcBridge.requestString(java.lang.String, java.lang.String)' on a null object reference
	at tkaxv7s.xposed.sesame.hook.ApplicationHook.requestString(ApplicationHook.java:655)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestRpcCall.consultForSendEnergyByAction(AntForestRpcCall.java:373)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.sendEnergyByAction(AntForestV2.java:1224)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.run(AntForestV2.java:302)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:13:45.966 ERROR: AntForestV2, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String tkaxv7s.xposed.sesame.rpc.RpcBridge.requestString(java.lang.String, java.lang.String)' on a null object reference
	at tkaxv7s.xposed.sesame.hook.ApplicationHook.requestString(ApplicationHook.java:655)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestRpcCall.query_forest_energy(AntForestRpcCall.java:404)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.medicalHealthFeeds(AntForestV2.java:1111)
	at tkaxv7s.xposed.sesame.model.task.antForest.AntForestV2.run(AntForestV2.java:306)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:25:08.447 ERROR: AntFarm, org.json.JSONException: No value for memo
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.hireAnimal(AntFarm.java:1733)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.run(AntFarm.java:330)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:33:46.133 ERROR: AntFarm, org.json.JSONException: No value for memo
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.hireAnimal(AntFarm.java:1733)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.run(AntFarm.java:330)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by TKaxv-7S** [comment]
在 v1.2.7.7-TK 版本已修复

**Comment by Norman45** [comment]
建议列表改成雇佣指定小鸡列表，而不是不雇佣列表，因为只想雇佣自己小号的小鸡
