### ISSUE TITLE
错误日志报错

### ISSUE THREAD

**Issue by shwk88888** [TKaxv-7S/Sesame-TK#149]
### 程序版本 / 框架版本 / 模块版本

Lsposed1.9.3 7301

### 系统版本 / Android版本

coloros Android14

### 详细描述问题发生的具体原因

![Screenshot_2024-07-04-16-59-43-39_a66f4987811f41f132433609e46be64d](https://github.com/TKaxv-7S/Sesame-TK/assets/144395838/5d2b0152-36dd-4fca-b6b6-9693626f955c)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

17:00:55.828 ERROR: AntFarm, org.json.JSONException: No value for memo
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.notifyFriend(AntFarm.java:1086)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.run(AntFarm.java:320)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

17:03:43.074 ERROR: AntStall, org.json.JSONException: No value for playingResult
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.taskList(AntStall.java:509)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:145)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

17:03:44.447 ERROR: AntStall, org.json.JSONException: No value for playingResult
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.taskList(AntStall.java:509)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:147)
	at tkaxv7s.xposed.sesame.data.ModelTask$1.run(ModelTask.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by TKaxv-7S** [comment]
木兰集市已失效导致，不用管，后面修复或者移除就没有了

**Comment by shwk88888** [comment]
多谢大神的回复，辛苦了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月04日 22:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TKaxv-7S/Sesame-TK] 错误日志报错 (Issue #149) |

木兰集市已失效导致，不用管，后面修复或者移除就没有了
