### ISSUE TITLE
蚂蚁保保障金不会自动收取

### ISSUE THREAD

**Issue by bocchi810** [TKaxv-7S/Sesame-TK#204]
### 程序版本 / 框架版本 / 模块版本

10.6.13/1.9.2/1.2.9Y-TK

### 系统版本 / Android版本

HyperOS/14

### 详细描述问题发生的具体原因

打开了“芝麻粒坚持攒保障金”也无法自动收取蚂蚁保保障金

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

00:02:45.073 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

00:32:32.968 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

01:02:44.880 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

01:32:56.519 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

02:03:10.791 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

02:33:22.666 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

03:03:37.136 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

03:33:49.175 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

04:04:01.825 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

04:34:13.407 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

05:04:26.696 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

05:34:37.195 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

06:04:49.183 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

06:35:20.795 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

06:56:00.411 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

07:56:15.702 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

08:26:37.048 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

08:56:39.938 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:26:48.657 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:56:59.276 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

10:27:10.755 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

10:57:21.063 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

11:27:30.732 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

11:57:41.260 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

12:27:51.180 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

12:58:01.524 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

13:28:12.088 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

13:58:20.592 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

14:28:31.908 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

14:58:46.664 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

15:28:55.250 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

15:59:01.517 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

16:29:10.455 ERROR: AntStall, org.json.JSONException: No value for astProjectVO
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.donate(AntStall.java:821)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.run(AntStall.java:162)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

</code></pre></details>

**Comment by Liujishou** [comment]
这个需要手动在生活记录里加入并开启自动，后续就会收取保障金了

**Comment by bocchi810** [comment]
> 这个需要手动在生活记录里加入并开启自动，后续就会收取保障金了

能给个详细路径吗，实在找不到，我尝试搜索这个功能也找不到

**Comment by baby1128** [comment]
芝麻信用-信用管理-生活记录-添加其他记录-坚持攒保障金

**Comment by bocchi810** [comment]
> 芝麻信用-信用管理-生活记录-添加其他记录-坚持攒保障金

怎么说呢，我这里的保障金指的是蚂蚁保-保障金
