### ISSUE TITLE
庄园无法收取小鸡饲料，提示代理

### ISSUE THREAD

**Issue by lingluan001** [TKaxv-7S/Sesame-TK#22]
### 程序版本 / 框架版本 / 模块版本

10.6.6 / LSP1.9.1 / 1.2.5.5TK

### 系统版本 / Android版本

ColorOS14 / Android14

### 详细描述问题发生的具体原因

只要开启庄园开关，就弹出VPN提示，手动收小鸡饲料时提示“人气大爆发请稍后再试”，并弹出VPN提示。在关闭庄园开关的情况下，手动收小鸡饲料情况一样。小鸡饲料无法收取。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

07:11:45.122 I/RUNTIME: Config, load config
07:11:45.124 I/RUNTIME: FileUtils, config.json文件不存在
07:11:45.154 I/RUNTIME: Config, java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2476)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1174)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566)
	at pansong291.xposed.quickenergy.util.Config.load(Config.java:381)
	at pansong291.xposed.quickenergy.ui.MainActivity$1.run(MainActivity.java:129)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:11:45.154 I/RUNTIME: Config, 配置文件格式有误，已重置配置文件
07:11:45.165 I/RUNTIME: Config, 重新格式化 config.json
07:11:45.177 I/RUNTIME: FileUtils, statisticsFile.json文件不存在
07:11:45.189 I/RUNTIME: Statistics, java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2476)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1174)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566)
	at pansong291.xposed.quickenergy.util.Statistics.load(Statistics.java:751)
	at pansong291.xposed.quickenergy.ui.MainActivity$1.run(MainActivity.java:130)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

07:11:45.189 I/RUNTIME: Statistics, 统计文件格式有误，已重置统计文件
07:11:45.194 I/RUNTIME: Statistics, 重新格式化 statistics.json
07:11:45.986 I/RUNTIME: Config, load config
07:13:39.986 I/RUNTIME: Config, load config

</code></pre></details>

**Comment by berebrn** [comment]
更新最新版本

**Comment by lingluan001** [comment]
已升级1.2.5.8，错误依旧

**Comment by TKaxv-7S** [comment]
> 已升级1.2.5.8，错误依旧

后面会更新一些版本移除影响森林、庄园、农场、新村等基础功能的副加功能，可能异常会少很多

**Comment by ritaferni** [comment]
已升级到最新版1.2.6-test7，还是如此。
支付宝从10.5.80开始有这个问题，一路升级至最新10.6.10，还是会弹出代理提示~

**Comment by ritaferni** [comment]
> 已升级到最新版1.2.6-test7，还是如此。 支付宝从10.5.80开始有这个问题，一路升级至最新10.6.10，还是会弹出代理提示~

补充：一旦有这个问题后，即使回退到80之前的老版支付宝，也是无法收取饲料，不收不弹提示、一收就弹。

**Comment by TKaxv-7S** [comment]
> 已升级到最新版1.2.6-test7，还是如此。 支付宝从10.5.80开始有这个问题，一路升级至最新10.6.10，还是会弹出代理提示~ 一旦有这个问题后，即使回退到80之前的老版支付宝，也是无法收取饲料，不收不弹提示、一收就弹。安装原版支付宝也会这样~

新版本 v1.2.6-test8-TK 已更新，优化了大量频繁的请求导致异常的问题，可以试试还有没有问题

**Comment by ritaferni** [comment]
> > 已升级到最新版1.2.6-test7，还是如此。 支付宝从10.5.80开始有这个问题，一路升级至最新10.6.10，还是会弹出代理提示~ 一旦有这个问题后，即使回退到80之前的老版支付宝，也是无法收取饲料，不收不弹提示、一收就弹。安装原版支付宝也会这样~
> 
> 新版本 v1.2.6-test8-TK 已更新，优化了大量频繁的请求导致异常的问题，可以试试还有没有问题

立马下载了8试试，很遗憾，问题照旧。

**Comment by TKaxv-7S** [comment]
> > > 已升级到最新版1.2.6-test7，还是如此。 支付宝从10.5.80开始有这个问题，一路升级至最新10.6.10，还是会弹出代理提示~ 一旦有这个问题后，即使回退到80之前的老版支付宝，也是无法收取饲料，不收不弹提示、一收就弹。安装原版支付宝也会这样~
> > 
> > 
> > 新版本 v1.2.6-test8-TK 已更新，优化了大量频繁的请求导致异常的问题，可以试试还有没有问题
> 
> 立马下载了8试试，很遗憾，问题照旧。

账号暂时被风控了，再等待一段时间应该就可以知道还有没有问题了

**Comment by Norman45** [comment]
频繁用加速卡，频繁领饲料可能有影响，建议加速卡用了八次就不加速了，饲料检测满了就不做领取操作

**Comment by ritaferni** [comment]
很诡异，昨天提示代理后我就把庄园关了，今天也没开，手动去庄园做完任务、点击领饲料，居然还提示“人气大爆发请稍后再试”，然后立马弹代理提示！！

**Comment by Norman45** [comment]
要用没有挂的手机保持24小时

**Comment by ritaferni** [comment]
> 要用没有挂的手机保持24小时

那太难了！而且就算手动正常了，可如果这个问题不修复，一开就提示，那也没意义啊！

**Comment by ritaferni** [comment]
我今天尝试解决了：先关模块，再进支付宝手动领就正常了，再启动模块就ok了
