### ISSUE TITLE
谁能帮我看一下跳VPN的是什么功能,我来把它关掉

### ISSUE THREAD

**Issue by mmmm525** [TKaxv-7S/Sesame-TK#265]
### 程序版本 / 框架版本 / 模块版本

LSPosed  1.9.2

### 系统版本 / Android版本

ColorOS 14.0    内核android13  Android版本14

### 详细描述问题发生的具体原因

02:29:02.086 ERROR: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at tkaxv7s.xposed.sesame.model.normal.base.BaseModel.initBeach(BaseModel.java:147)
	at tkaxv7s.xposed.sesame.model.normal.base.BaseModel.lambda$initData$0(BaseModel.java:96)
	at tkaxv7s.xposed.sesame.model.normal.base.BaseModel$$ExternalSyntheticLambda0.run(Unknown Source:0)
	at java.lang.Thread.run(Thread.java:1012)

13:01:31.488 ERROR: AntStall, org.json.JSONException: No value for resultCode
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.openShop(AntStall.java:443)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.friendHomeOpen(AntStall.java:466)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.rankCoinDonate(AntStall.java:428)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.openShop(AntStall.java:396)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.lambda$closeShop$1$AntStall(AntStall.java:360)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$ChildModelTask.run(ModelTask.java:300)
	at tkaxv7s.xposed.sesame.data.task.SystemChildTaskExecutor.lambda$addChildTask$0(SystemChildTaskExecutor.java:44)
	at tkaxv7s.xposed.sesame.data.task.SystemChildTaskExecutor$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:290)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

15:01:37.773 ERROR: AntStall, org.json.JSONException: No value for resultCode
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.openShop(AntStall.java:443)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.friendHomeOpen(AntStall.java:466)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.rankCoinDonate(AntStall.java:428)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.openShop(AntStall.java:396)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall.lambda$closeShop$1$AntStall(AntStall.java:360)
	at tkaxv7s.xposed.sesame.model.task.antStall.AntStall$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at tkaxv7s.xposed.sesame.data.task.ModelTask$ChildModelTask.run(ModelTask.java:300)
	at tkaxv7s.xposed.sesame.data.task.SystemChildTaskExecutor.lambda$addChildTask$0(SystemChildTaskExecutor.java:44)
	at tkaxv7s.xposed.sesame.data.task.SystemChildTaskExecutor$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:290)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
以上是异常日志  翻译出来的是        这个错误是一个JSON解析异常，发生在AntStall类的openShop方法中。错误的原因是当尝试从一个JSONObject中获取名为"resultCode"的值时，该值不存在。因此，它触发了一个org.json.JSONException。解决这个问题可能需要检查JSON对象是否确实包含了一个名为"resultCode"的键，并且该值是否被正确地填充。如果JSON对象来自外部响应，可能需要确保响应格式是预期的，并且没有丢失任何重要字段。  但是我还是不知道具体是哪个功能跳VPN

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
ChatGPT回答得比我好

**Comment by mmmm525** [comment]
> 新村摆摊的，看你是不是选了没开通的好友或者新村异常了。

牛啊  果然是新村  我设置的选中不摆摊,然后全部没勾选  然后应该是芝麻粒选到了没开通新村的,这个希望作者可以看到,摆摊之前检测一下呢,或者直接用上面的随机摆摊

**Comment by TKaxv-7S** [comment]
已修复，在下个版本更新
