### ISSUE TITLE
双开失效

### ISSUE THREAD

**Issue by lianggiraffe** [TKaxv-7S/Sesame-TK#8]
### 程序版本 / 框架版本 / 模块版本

支付宝(10.6.3.8000) Lsposed(1.9.2) 芝麻粒(1.2.5)

### 系统版本 / Android版本

澎湃1.0.2.0 a14

### 详细描述问题发生的具体原因

双开版本芝麻粒无效 上版本(1.2.4.12)正常使用

### 提供模块问题 Log 或必要 Log

23:21:02.486 I/ERROR: Statistics, java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2476)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1174)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:628)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:144)
	at tkaxv7s.xposed.sesame.ui.MainActivity$2.run(MainActivity.java:120)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

23:22:39.851 I/ERROR: ConfigV2, java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2476)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1174)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566)
	at tkaxv7s.xposed.sesame.data.ConfigV2.load(ConfigV2.java:270)
	at tkaxv7s.xposed.sesame.ui.SettingsActivity.onCreate(SettingsActivity.java:60)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by lianggiraffe** [comment]
抱歉 是我憨批了
