### ISSUE TITLE
支付宝频繁弹代理软件或VPN

### ISSUE THREAD

**Issue by MJRweb** [TKaxv-7S/Sesame-TK#92]
### 程序版本 / 框架版本 / 模块版本

程序版本10.6.8.8000     框架版本 lsp1.9.2     模块版本v1.2.6.5-TK    

### 系统版本 / Android版本

澎湃OS / Android14

### 详细描述问题发生的具体原因

动不动就弹，如图，貌似不影响模块使用，日志文件看不出来啥，个人理解，支付宝检测到了hook？
![Screenshot_2024-06-30-16-58-15-725_com eg android AlipayGphone](https://github.com/TKaxv-7S/Sesame-TK/assets/74905147/19b16fc3-100b-44db-88c5-acfe3d964657)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by MJRweb** [comment]
18:07:30.782 I/ERROR: Statistics, java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2402)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1100)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1492)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:772)
	at tkaxv7s.xposed.sesame.ui.MainActivity.onResume(MainActivity.java:144)
	at tkaxv7s.xposed.sesame.ui.MainActivity$2.run(MainActivity.java:120)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

18:07:33.909 I/ERROR: ConfigV2, java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2402)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1100)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1492)
	at tkaxv7s.xposed.sesame.data.ConfigV2.load(ConfigV2.java:149)
	at tkaxv7s.xposed.sesame.ui.SettingsActivity.onCreate(SettingsActivity.java:30)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

18:10:03.319 I/ERROR: Statistics, java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2402)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1100)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1492)
	at tkaxv7s.xposed.sesame.util.Statistics.load(Statistics.java:772)
	at tkaxv7s.xposed.sesame.hook.ApplicationHook.initHandler(ApplicationHook.java:573)
	at tkaxv7s.xposed.sesame.hook.ApplicationHook.access$200(ApplicationHook.java:38)
	at tkaxv7s.xposed.sesame.hook.ApplicationHook$3.afterHookedMethod(ApplicationHook.java:273)
	at m.AYZUMmipliayiw.cnTDT.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.onCreate(Unknown Source:8)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4878)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:35)
	at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:49)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

18:10:13.741 I/ERROR: AntFarm, org.json.JSONException: No value for memo
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.receiveFarmTaskAward(AntFarm.java:835)
	at tkaxv7s.xposed.sesame.model.task.antFarm.AntFarm.run(AntFarm.java:280)
	at tkaxv7s.xposed.sesame.data.ModelTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)

18:10:33.391 I/ERROR: AntFarm, org.json.JSONException: No value for memo
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at tkaxv7s.xposed.sesame.model.task.antFarm.Ant

**Comment by MJRweb** [comment]
@TKaxv-7S 模块设置更改，重新刷新hook  app第一次100%概率弹出被检测

**Comment by MJRweb** [comment]
貌似1.2.6.7tk已经解决

**Comment by MJRweb** [comment]
解决？
